/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAuction } from "./MockAuction";
export type { MockAuctionAdapter } from "./MockAuctionAdapter";
export type { MockVault } from "./MockVault";
