/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICollateralManager__factory } from "./ICollateralManager__factory";
export { LendingPool__factory } from "./LendingPool__factory";
