/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockChainlinkAggregator,
  MockChainlinkAggregatorInterface,
} from "../../../../contracts/mocks/MockContracts.sol/MockChainlinkAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "initialPrice",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "newPrice",
        type: "int256",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60803461008b57601f61022338819003918201601f19168301916001600160401b038311848410176100905780849260209460405283398101031261008b575161005c604051672c537f24dd61b88e6020820152602081526100a6565b6100796040516701f1baba2768537b6020820152602081526100a6565b60005560405161016190816100c28239f35b600080fd5b634e487b7160e01b600052604160045260246000fd5b604081019081106001600160401b038211176100905760405256fe60806040818152600436101561001457600080fd5b600091823560e01c90816350d25bcd1461008d575063f7a308061461003857600080fd5b34610089576020366003190112610089578061006961008192516715242e628118ab5b6020820152602081526100f9565b51676b2874fb50b1e7476020820152602081526100f9565b600435815580f35b5080fd5b8284346100f657806003193601126100f6576100ba60209367e541800909838ddc858201528481526100f9565b6100d48251674047d1530eb69dfa858201528481526100f9565b6100ee825167b439314f58fd0c41858201528481526100f9565b549051908152f35b80fd5b6040810190811067ffffffffffffffff82111761011557604052565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220a8e047ed0dcb06a4d1dcc6cd013ef6876a50d0bbde77cbf11a9eb961b111720164736f6c63430008140033";

type MockChainlinkAggregatorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockChainlinkAggregatorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockChainlinkAggregator__factory extends ContractFactory {
  constructor(...args: MockChainlinkAggregatorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    initialPrice: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(initialPrice, overrides || {});
  }
  override deploy(
    initialPrice: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(initialPrice, overrides || {}) as Promise<
      MockChainlinkAggregator & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockChainlinkAggregator__factory {
    return super.connect(runner) as MockChainlinkAggregator__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockChainlinkAggregatorInterface {
    return new Interface(_abi) as MockChainlinkAggregatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockChainlinkAggregator {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockChainlinkAggregator;
  }
}
