version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: valuation-postgres
    environment:
      POSTGRES_DB: bastion_valuation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - valuation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: valuation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - valuation-network
    command: redis-server --appendonly yes --requirepass redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Valuation API
  valuation-api:
    build:
      context: ../../
      dockerfile: apps/valuation-api/Dockerfile
    container_name: valuation-api
    environment:
      NODE_ENV: production
      PORT: 3001
      
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres_password
      DB_DATABASE: bastion_valuation
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      REDIS_DB: 0
      
      # JWT
      JWT_SECRET: your-jwt-secret-key-change-in-production
      JWT_EXPIRES_IN: 24h
      
      # Valuation
      VALUATION_SIGNING_KEY: your-valuation-signing-key-change-in-production
      
      # External APIs (optional)
      OPENSEA_API_KEY: your-opensea-api-key
      COINGECKO_API_KEY: your-coingecko-api-key
      
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - valuation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: valuation-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - valuation-api
    networks:
      - valuation-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  valuation-network:
    driver: bridge