/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionAdapterSol from "./AuctionAdapter.sol";
export type { auctionAdapterSol };
import type * as circleFactorySol from "./CircleFactory.sol";
export type { circleFactorySol };
import type * as circleTreasurySol from "./CircleTreasury.sol";
export type { circleTreasurySol };
import type * as mocks from "./mocks";
export type { mocks };
export type { BastionProtocol } from "./BastionProtocol";
export type { CircleVault } from "./CircleVault";
export type { ICircle } from "./ICircle";
