/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockAuctionAdapter,
  MockAuctionAdapterInterface,
} from "../../../../contracts/mocks/MockContracts.sol/MockAuctionAdapter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "auctionId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "minAmountOut",
        type: "uint256",
      },
    ],
    name: "BidPlaced",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "auctionId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minAmountOut",
        type: "uint256",
      },
    ],
    name: "placeBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100165761012d908161001c8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c635e62be2514602857600080fd5b3460c257606036600319011260c25760607f6e071b3ecca1348e93201ab40ec33e13c163fc1ac7969101e82a6f3e413381c5916074602091675ae3c0add460c73b8382015282815260c6565b608d604051675e9eda31ba27c8868382015282815260c6565b60a66040516782e33fa2bffc13528382015282815260c6565b604051906004358252602435908201526044356040820152a180f35b5080fd5b6040810190811067ffffffffffffffff82111760e157604052565b634e487b7160e01b600052604160045260246000fdfea26469706673582212202dfcaf9de8fd69297becc335064b2b2d86f35d3f0b04b9063673acceaa62dcd664736f6c63430008140033";

type MockAuctionAdapterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAuctionAdapterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAuctionAdapter__factory extends ContractFactory {
  constructor(...args: MockAuctionAdapterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockAuctionAdapter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockAuctionAdapter__factory {
    return super.connect(runner) as MockAuctionAdapter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAuctionAdapterInterface {
    return new Interface(_abi) as MockAuctionAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockAuctionAdapter {
    return new Contract(address, _abi, runner) as unknown as MockAuctionAdapter;
  }
}
