version: '3.8'

services:
  relayer:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://bastion:bastion123@postgres:5432/bastion_relayer
      - REDIS_URL=redis://redis:6379
      - DOMA_RPC_URL=${DOMA_RPC_URL}
      - DOMA_WS_URL=${DOMA_WS_URL}
      - DOMA_VAULT_ADDRESS=${DOMA_VAULT_ADDRESS}
      - DOMA_CHAIN_ID=${DOMA_CHAIN_ID}
      - FUJI_RPC_URL=${FUJI_RPC_URL}
      - FUJI_MIRROR_NFT_ADDRESS=${FUJI_MIRROR_NFT_ADDRESS}
      - RELAYER_PRIVATE_KEY=${RELAYER_PRIVATE_KEY}
      - PORT=3001
      - LOG_LEVEL=info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bastion_relayer
      - POSTGRES_USER=bastion
      - POSTGRES_PASSWORD=bastion123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bastion"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:
